name: HTML CSS CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HTMLHint
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          files: 'index.html'

